spring:
  application:
    name: QRust-BE


crypto:
  aes:
    key: ${CRYPTO_AES_KEY}  # Base64 인코딩된 32바이트 키 (AES-256)

minio:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucketName: ${MINIO_BUCKET_NAME}