spring:
  application:
    name: QRust-BE

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create

crypto:
  aes:
    key: ${CRYPTO_AES_KEY}  # Base64 인코딩된 32바이트 키 (AES-256)

minio:
  endpoint: http://mayfifth99.store:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucketName: qrust-bucket