spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qrust-harvey
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션
    open-in-view: false #OSIV 를 true로 설정하면, request가 반환될 때 까지 커넥션을 보유

logging.level:
  org.hibernate.SQL: debug # 이거 끄면 format_sql 적용 안됨
#  org.hibernate.type: trace

crypto:
  aes:
    key: ${CRYPTO_AES_KEY}  # Base64 인코딩된 32바이트 키 (AES-256)

google:
  safe-browsing:
    api:
      key: ${GOOGLE_SAFE_BROWSING_API_KEY}
      base-url: ${GOOGLE_SAFE_BROWSING_BASE_URL}

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucketName: qrust-bucket
