spring:
  application:
    name: QRust-BE
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  data:
    redis:
      host: localhost
      port: 6379

    jpa:
      hibernate:
        ddl-auto: create

crypto:
  aes:
    key: ${CRYPTO_AES_KEY}  # Base64 인코딩된 32바이트 키 (AES-256)

google:
  safe-browsing:
    api:
      key: ${GOOGLE_SAFE_BROWSING_API_KEY}
      base-url: ${GOOGLE_SAFE_BROWSING_BASE_URL}

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucketName: qrust-bucket
  prefix: ${DOMAIN_ADDRESS}

jwt:
  secret: ${JWT_SECRET}

ai:
  model:
    base-url: ${AI_MODEL_BASE_URL}
