name: PR CI Pipeline

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest # Github Hosted Runner
    env:
      CRYPTO_AES_KEY: ${{ secrets.CRYPTO_AES_KEY }}
      GOOGLE_SAFE_BROWSING_API_KEY: ${{ secrets.GOOGLE_SAFE_BROWSING_API_KEY }}
      GOOGLE_SAFE_BROWSING_BASE_URL: ${{ secrets.GOOGLE_SAFE_BROWSING_BASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      AI_MODEL_BASE_URL: ${{ secrets.AI_MODEL_BASE_URL }}
      DOMAIN_ADDRESS: ${{ secrets.DOMAIN_ADDRESS }}

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: gradle # gradle 의존성 캐싱으로 빌드 시간 최적화

      - name: Grant Execute Permission To Gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: |
          ./gradlew clean test bootJar -DexcludeTags=minio
