name: PR-MERGE-CD-PIPELINE
on:
  push:
    branches:
      - develop
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CRYPTO_AES_KEY: ${{ secrets.CRYPTO_AES_KEY }}
      GOOGLE_SAFE_BROWSING_API_KEY: ${{ secrets.GOOGLE_SAFE_BROWSING_API_KEY }}
      GOOGLE_SAFE_BROWSING_BASE_URL: ${{ secrets.GOOGLE_SAFE_BROWSING_BASE_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -f qrust-api/Dockerfile -t ${{ secrets.DOCKERHUB_USER_NAME }}/QRust-image:latest .

      - name: Docker Hub Login
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER_NAME }}" --password-stdin

      - name: Docker Image Push
        run: docker push ${{ secrets.DOCKERHUB_USER_NAME}}/QRust-image:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest


    steps:
      - name: SSH 연결 및 배포
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USER_NAME }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            docker rmi -f ${{ secrets.DOCKERHUB_USER_NAME }}/qrust-image:latest
            docker pull ${{ secrets.DOCKERHUB_USER_NAME }}/qrust-image:latest
            cd /home/ubuntu/qrust/docker/app
            docker compose up -d
            docker image prune -f
