name: Workflow Dispatch Deploy # 수동 CD 파이프라인

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '배포할 태그를 입력하세요 (ex: v1.0.0)'
        required: true
        default: v1.0.0
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -f qrust-api/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/qrust-image:${{ github.event.inputs.tag }} .

      - name: Docker Hub Login
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker Image Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/qrust-image:${{ github.event.inputs.tag }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH 연결 및 배포
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USER_NAME }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/qrust-image:${{ github.event.inputs.tag }}
            docker stop qrust-container || true
            docker rm qrust-container || true
            docker run -d --name qrust-container -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/qrust-image:${{ github.event.inputs.tag }}
